# Generated by Django 3.0.3 on 2020-08-15 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200815_0844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
