# Generated by Django 3.0.3 on 2020-08-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200815_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePicture',
            field=models.ImageField(default='default.jpg', upload_to='users'),
        ),
    ]
